### ISSUE TITLE
Question about identifierField and custom primary keys

### ISSUE THREAD

**Issue by NegaMorgan** [konstantinzolotarev/sails-hook-adminpanel#17]
Hi,

I'm new to Sails and trying sails-hook-adminpanel, but I'm having a problem with the Action links in the admin panel. They are all coming up as undefined. Hopefully you can help.

I'm using a MySQL DB with pre-existing columns and data, so in Sails I am setting the primary key manually. The primary key is 'asset_id'.

    // api/models/projects.js
    attributes: { asset_id : { type: 'integer', primaryKey: true, unique: true } ... }

In the `/docs` for sails-hook-adminpanel, it says I can set a custom primary key with the identifierField option. I have tried this:

    // config/adminpanel.js
    module.exports.adminpanel = {
        instances: {

            project: {

                title: 'Projects',
                model: 'Project',
                identifierField: 'asset_id',

                list: ... }}}

And this:

    module.exports.adminpanel = {
        identifierField: 'asset_id',
        instances: {

            project: {

                title: 'Projects',
                model: 'Project',

                list: ... }}}

But both give me with the same /undefined links when I `sails lift` the app. There are no js errors, and the admin edit/create/view endpoints are available if I type them in (with existing keys), but I'd love to get the Action links working.

Any idea what I'm doing wrong? Or is it a bug, maybe? Any help is much appreciated.

Also, I'm using Sails v0.11.0, Node v0.12.0

**Comment by konstantinzolotarev** [comment]
Checking.
Will update tomorrow morning.

**Comment by konstantinzolotarev** [comment]
Updated sources and released new version.
Please validate.

Also correct configuration for identifier should be set like this: 
```javascript
module.exports.adminpanel = {
    identifierField: 'asset_id',
    instances: {

        project: {

            title: 'Projects',
            model: 'Project',
 
       }
    }
}
```

**Comment by NegaMorgan** [comment]
Confirmed, recommended method works for me in v0.1.23. Thanks!

Would be awesome to have per-model identifierField in a future release, if you think that would be useful as well.

**Comment by konstantinzolotarev** [comment]
Working on this. Actually testing.
