### ISSUE TITLE
 Error: Cannot use `adminpanel` hook without the `views` hook.

### ISSUE THREAD

**Issue by elidiazgt** [konstantinzolotarev/sails-hook-adminpanel#25]
How i can enable or install the views hook?

**Comment by konstantinzolotarev** [comment]
There is no such feature right now. 

Could you please give some more description. I'm working on new UI and could add this feature as well.

**Comment by konstantinzolotarev** [comment]
Actually view hook should be installed form default. What version of sails.js do you use ? Do you have `config/views.js` file in your project ?

**Comment by dardalan** [comment]
@konstantinzolotarev hey, i have the same issue, i have the file config/views.js. sails version 0.11.0, and admin-panel 0.1.23

**Comment by konstantinzolotarev** [comment]
@dardalan You don't have UI for adminpanel rendered ? Am I right ?

**Comment by dardalan** [comment]
@konstantinzolotarev you are right, by the way i've fixed this issue, after i had new one that admin panel could work only with jade, ok i replace engine to jade, and then after sails lift i tried to go to http://localhost:1337/admin but still not be able to have UI for admin panel rendered(

**Comment by konstantinzolotarev** [comment]
@dardalan yes this is very old version of Adminpanel. 
You could try to use `npm install --save sails-hook-adminpanel@beta` 

It supports jade/ejs and much more field types than prev one.
