### ISSUE TITLE
How can enable and disable the adminpanel?

### ISSUE THREAD

**Issue by elidiazgt** [konstantinzolotarev/sails-hook-adminpanel#26]
Exist a flag that i can use in enviroment files?

**Comment by konstantinzolotarev** [comment]
Nope. 
Will add

**Comment by konstantinzolotarev** [comment]
In new version. v1.0.1 (not released yet) 
You will be able to use `config/adminpanel.js` 

```javascript
module.exports.adminpanel = false;
```

To disable admin panel
