### ISSUE TITLE
Когда будет поддержка ejs?

### ISSUE THREAD

**Issue by misterjt** [konstantinzolotarev/sails-hook-adminpanel#33]
Идея просто восхитительна! Но в проектах использую ejs. Вижу, у вас в папке view даже есть наработки, но там какие-то проблемы, может вам нужна помощь?

У меня такая ошибка получается
```
Sending 500 ("Server Error") response: 
 TypeError: /opt/src/client/node_modules/sails-hook-adminpanel/views/ejs/list.ejs:1
 >> 1| <% include head %>
    2| 
    3| <div class="horizontal layout">
    4|     <div class="flex">

Cannot read property 'hasFlash' of undefined
```

**Comment by konstantinzolotarev** [comment]
Поддержка **ejs** уже есть, просто она только в бетта версии.
Можно установить через `npm i sails-hook-adminpanel@beta --save`
