### ISSUE TITLE
What way to add admin assets?

### ISSUE THREAD

**Issue by KirillSuhodolov** [konstantinzolotarev/sails-hook-adminpanel#37]
After adding this hook and starting application no assets were distribute. 

Digging in docs can't help.

What should I add in to config or run some hook to add them?

![Assets](http://dl2.joxi.net/drive/0006/3189/441461/151106/aece668d06.jpg)

**Comment by konstantinzolotarev** [comment]
Seems that assets didn't copy to your assets directory.
What version of hook do you use ? And what OS ?

**Comment by KirillSuhodolov** [comment]
@konstantinzolotarev 
v sails 0.11
hook is last from master
os x

**Comment by KirillSuhodolov** [comment]
Admin directory copied to assets, but it under admin namespace and sails don't distribute it.
May be you have custom grunt tasks?

**Comment by konstantinzolotarev** [comment]
No there are no any custom grunt task.
Could you try to use this setting:
```
assets: 'link'
```

https://github.com/konstantinzolotarev/sails-hook-adminpanel/blob/master/docs/Assets.md

2015-11-06 18:48 GMT+06:00 Kirill <notifications@github.com>:

> Admin directory copied to assets, but it under admin namespace and sails
> don't distribute it.
> May be you have custom grunt tasks?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/konstantinzolotarev/sails-hook-adminpanel/issues/37#issuecomment-154402018>
> .
>



-- 
Regards.
Zolotarev Konstantin
http://gplus.to/kzolotarev
konstantin.zolotarev@gmail.com

**Comment by KirillSuhodolov** [comment]
@konstantinzolotarev same problem

**Comment by konstantinzolotarev** [comment]
@KirillSuhodolov Strange. Could you please send me content of your `.sailsrc` file ?

**Comment by KirillSuhodolov** [comment]
{
  "generators": {
    "modules": {}
  }
}

I create new project, all looks same, .sailsrc same, but version is 0.11.2. All assets work correctly.

**Comment by konstantinzolotarev** [comment]
@KirillSuhodolov Did you installed it using `npm i --save sails-hook-adminpanel` or `npm i --save sails-hook-adminpanel@beta` ?

**Comment by KirillSuhodolov** [comment]
``
npm i --save sails-hook-adminpanel
``

**Comment by konstantinzolotarev** [comment]
@KirillSuhodolov you might be using `ejs` as a template engine ? 
The old version of admin panel does not support `ejs`. Please try `sails-hook-adminpanel@beta`. It has `ejs` support and should work properly.

**Comment by KirillSuhodolov** [comment]
It's not issue with jade or ejs. I tried them all.
At new test project assets works with bots, at old one, nothing.
I am comparing grunt tasks at projects.

**Comment by KirillSuhodolov** [comment]
[Dashboard](http://dl2.joxi.net/drive/0006/3189/441461/151106/be2d6a3f3e.jpg)

I update for version 1.0.10 and ejs and it looks that works

**Comment by konstantinzolotarev** [comment]
@KirillSuhodolov In any case you can easily copy [assets](https://github.com/konstantinzolotarev/sails-hook-adminpanel/tree/master/assets) folder to `assets/admin` of your project
