### ISSUE TITLE
Authenticated 

### ISSUE THREAD

**Issue by KirillSuhodolov** [konstantinzolotarev/sails-hook-adminpanel#38]
I deep into the code and didn't find any built-in authenticated. What the best way to add it?

P.S.
Currently I am using sails.js as api with token authentication.

**Comment by konstantinzolotarev** [comment]
@KirillSuhodolov https://github.com/konstantinzolotarev/sails-hook-adminpanel/blob/master/docs/Security.md

**Comment by KirillSuhodolov** [comment]
I mean pages for authentication.

**Comment by konstantinzolotarev** [comment]
There is no login form in adminpanel.
It uses your project policy to protect it.
So you could create a additional field in user object and use your login
page. Or you could define additional auth system on http auth.
