### ISSUE TITLE
How to add authentication for that "http://localhost:1337/admin " url . Please let me know

### ISSUE THREAD

**Issue by Salman18** [konstantinzolotarev/sails-hook-adminpanel#56]

**Comment by konstantinzolotarev** [comment]
https://github.com/konstantinzolotarev/sails-hook-adminpanel/blob/master/docs/Security.md

**Comment by Salman18** [comment]
How to login to the admin section.

Where I have to write Routes.

**Comment by Salman18** [comment]
Hi,


I am writing this mail to inform you that I added as mentioned in
security.md but I don't know how to login to admin. I have attached
screenshot please have a look at that.

It Would be glad if you tell how to admin users by logging in. what is the
username and password to access?

PFA.

Thanks and Regards
Salman

**Comment by konstantinzolotarev** [comment]
@Salman18 Do you have sample somewhere ? I don't see any attached files

**Comment by Salman18** [comment]
Actually I added as you mentioned in security.md.

Now my question is how to login as admin to see all users.

Where I have to login.

Thanks and regards,
Salman khan A

**Comment by konstantinzolotarev** [comment]
You have to create login process by yourself. this module relay on default sails.js permissions and security model.
